# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='학년')),
                ('middle_unit', models.CharField(max_length=20, verbose_name='중단원')),
                ('small_unit', models.CharField(max_length=20, verbose_name='소단원')),
                ('index', models.IntegerField(verbose_name='순번')),
            ],
        ),
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_day', models.DateField(blank=True, verbose_name='날짜')),
                ('come_status', models.IntegerField(blank=True, choices=[(3, 'good'), (2, 'normal'), (1, 'bad')], verbose_name='출결')),
                ('homework_complete', models.IntegerField(blank=True, choices=[(3, 'good'), (2, 'normal'), (1, 'bad')], verbose_name='과제여부')),
                ('homework_status', models.CharField(blank=True, max_length=200, verbose_name='과제상태')),
                ('contents', models.CharField(blank=True, max_length=200, verbose_name='학습내용')),
                ('test1', models.IntegerField(blank=True, verbose_name='소단원테스트점수')),
                ('test1_content', models.CharField(blank=True, max_length=200, verbose_name='소단원테스트내용')),
                ('test2', models.IntegerField(blank=True, verbose_name='중단원테스트점수')),
                ('test2_content', models.CharField(blank=True, max_length=200, verbose_name='중단원테스트내용')),
                ('test3', models.IntegerField(blank=True, verbose_name='대단원테스트점수')),
                ('test3_content', models.CharField(blank=True, max_length=200, verbose_name='대단원테스트내용')),
                ('note', models.CharField(blank=True, max_length=1500, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='학생이름')),
                ('shool_name', models.CharField(max_length=20, verbose_name='학교')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('come_day', models.CharField(blank=True, max_length=10, verbose_name='등원요일')),
                ('status', models.BooleanField(default=True, verbose_name='등록상태')),
            ],
        ),
        migrations.AddField(
            model_name='dailynote',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Student', verbose_name='학생이름'),
        ),
    ]
