# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynote',
            name='come_status',
            field=models.IntegerField(blank=True, choices=[(3, 'good'), (2, 'normal'), (1, 'bad')], null=True, verbose_name='출결'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='homework_complete',
            field=models.IntegerField(blank=True, choices=[(3, 'good'), (2, 'normal'), (1, 'bad')], null=True, verbose_name='과제여부'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='test1',
            field=models.IntegerField(blank=True, null=True, verbose_name='소단원테스트점수'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='test2',
            field=models.IntegerField(blank=True, null=True, verbose_name='중단원테스트점수'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='test3',
            field=models.IntegerField(blank=True, null=True, verbose_name='대단원테스트점수'),
        ),
    ]
